language: node_js
node_js:
  - 9
  - 8
cache:
  directories:
    - node_modules

install:
  - yarn install
env:
  global:
    - CC_TEST_REPORTER_ID=66e05412423a81a7d394b4351956977f7137e7c0bc2bb690fa1c2515ec6218c9

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn lint
  - yarn build
  - yarn test

after_script:
  - ./cc-test-reporter upload-coverage -i coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
